---
- name: provision
  hosts: all
  remote_user: root
  roles:
    - user
    - zzet.rbenv
    - nodejs
    - role: geerlingguy.mysql
      when: install_mysql|bool
    - role: geerlingguy.postgresql
      when: install_postgresql|bool
    - nginxinc.nginx
    - geerlingguy.passenger
    - geerlingguy.certbot

# uncomment this when you setup an app
# - name: deploy
#   hosts: all
#   remote_user: "{{ deploy_user }}"
#   gather_facts: no
#   roles:
#     - { role: deploy, tags: ['deploy'] }
