---
- name: provision
  hosts: all
  remote_user: root
  roles:
    - user
    - zzet.rbenv
    - role: nodejs
      when: install_nodejs|bool
    - role: geerlingguy.mysql
      when: install_mysql|bool
    - role: geerlingguy.postgresql
      when: install_postgresql|bool
    - geerlingguy.passenger
    - role: geerlingguy.certbot
      when: use_ssl|bool
    - role: s3cmd
      when: use_s3cmd|bool

# uncomment this when you setup an app
# - name: deploy
#   hosts: all
#   remote_user: "{{ deploy_user }}"
#   gather_facts: no
#   roles:
#     - { role: deploy, tags: ['deploy'] }
